<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>BrowserService</RootNamespace>
    <DefineConstants>$(DefineConstants);_PUBLISH_CHROMEDRIVER</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Selenium.Support" Version="4.44.0" />
    <PackageReference Include="Selenium.WebDriver" Version="4.44.0" />
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="148.0.7778.17800" />
    <PackageReference Include="SeleniumStealth.NET" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Markdown2Html\Markdown2Html.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <None Update="javascript\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
